from __future__ import annotations
import sys
import os
import math
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from dataclasses import dataclass, field
from typing import FrozenSet, List, Dict, Optional, Tuple
import numpy as np


# ═══════════════════════════════════════════════════════════════════════════════
# 1.  DATA STRUCTURES
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class FormalContext:
    """
    Formal context K = (G, M, I)  [Ganter & Wille 1999, Def. 1]

    objects    : G — list of object identifiers (KB record IDs)
    attributes : M — list of attribute names (CP-domain keywords)
    relation   : |G|×|M| boolean incidence matrix  I ⊆ G × M
    object_data: mapping id → full record dict for downstream use
    """
    objects:     List[str]
    attributes:  List[str]
    relation:    np.ndarray       # bool matrix [|G| × |M|]
    object_data: Dict             # id -> full record dict

    # ── Galois connection operators ──────────────────────────────────────────

    def object_prime(self, obj_set: FrozenSet[str]) -> FrozenSet[str]:
        """
        A' = { m ∈ M | ∀g ∈ A, (g,m) ∈ I }  (Eq. 12)

        The set of attributes shared by ALL objects in obj_set.
        Empty input → all attributes (top element of the lattice).
        """
        if not obj_set:
            return frozenset(self.attributes)
        idx = [self.objects.index(g) for g in obj_set if g in self.objects]
        if not idx:
            return frozenset()
        mask = np.all(self.relation[idx, :], axis=0)
        return frozenset(a for a, v in zip(self.attributes, mask) if v)

    def attribute_prime(self, attr_set: FrozenSet[str]) -> FrozenSet[str]:
        """
        B' = { g ∈ G | ∀m ∈ B, (g,m) ∈ I }  (Eq. 13)

        The set of objects that have ALL attributes in attr_set.
        Empty input → all objects (top element by extent).
        """
        if not attr_set:
            return frozenset(self.objects)
        idx = [self.attributes.index(m) for m in attr_set if m in self.attributes]
        if not idx:
            return frozenset()
        mask = np.all(self.relation[:, idx], axis=1)
        return frozenset(g for g, v in zip(self.objects, mask) if v)

    # ── Derived operations ──────────────────────────────────────────────────

    def closure(self, attr_set: FrozenSet[str]) -> FrozenSet[str]:
        """
        Attribute closure: B'' = (B')' — the intent of the concept
        generated by attr_set.  Idempotent: (B'')'' = B''.
        Used by NextClosure for canonical implication base.
        """
        return self.object_prime(self.attribute_prime(attr_set))

    def is_closed(self, attr_set: FrozenSet[str]) -> bool:
        """B is closed iff B'' = B  (B is an intent of some formal concept)."""
        return self.closure(attr_set) == attr_set

    def concept_from_intent(self, intent: FrozenSet[str]) -> Tuple[FrozenSet, FrozenSet]:
        """Return the formal concept (A,B) whose intent equals the closure of intent."""
        B = self.closure(intent)
        A = self.attribute_prime(B)
        return A, B

    def concept_from_extent(self, extent: FrozenSet[str]) -> Tuple[FrozenSet, FrozenSet]:
        """Return the formal concept (A,B) generated by extent."""
        A = self.object_prime(extent)           # A'  (= intent B)
        B = self.attribute_prime(A)             # B'  (= closed extent A'')
        return B, A


@dataclass
class FuzzyFormalContext:
    """
    Fuzzy formal context  K_f = (G, M, I_f)
    I_f : G × M → [0,1]   (Singh et al. 2016 Def. 4; Poelmans et al. 2013 §5.4.1)

    Used for handling vague or partially matching problem specifications.
    Membership degrees computed from term-frequency in record corpus.
    """
    objects:    List[str]
    attributes: List[str]
    relation_f: np.ndarray    # float matrix [|G| × |M|], values ∈ [0,1]
    object_data: Dict

    @classmethod
    def from_crisp(cls, ctx: FormalContext) -> "FuzzyFormalContext":
        """Convert crisp FormalContext → FuzzyFormalContext (0→0.0, 1→1.0)."""
        return cls(
            objects=ctx.objects,
            attributes=ctx.attributes,
            relation_f=ctx.relation.astype(float),
            object_data=ctx.object_data,
        )

    def fuzzy_object_prime(
        self, obj_set: FrozenSet[str], threshold: float = 0.5
    ) -> Dict[str, float]:
        """
        Fuzzy A' using Łukasiewicz t-norm (min):
            µ_{A'}(m) = min_{g ∈ A} I_f(g,m)
        Returns {attribute: membership_degree} for degrees ≥ threshold.
        """
        if not obj_set:
            return {a: 1.0 for a in self.attributes}
        idx = [self.objects.index(g) for g in obj_set if g in self.objects]
        if not idx:
            return {}
        memberships = np.min(self.relation_f[idx, :], axis=0)
        return {a: float(v) for a, v in zip(self.attributes, memberships) if v >= threshold}

    def to_crisp(self, threshold: float = 0.5) -> FormalContext:
        """Defuzzify to crisp FormalContext at threshold."""
        return FormalContext(
            objects=self.objects,
            attributes=self.attributes,
            relation=(self.relation_f >= threshold),
            object_data=self.object_data,
        )


@dataclass
class FormalConcept:
    """
    Formal concept C = (A, B)  [Ganter & Wille 1999, Def. 2]

    extent  A ⊆ G : maximal set of objects sharing all attributes in B
    intent  B ⊆ M : maximal set of attributes shared by all objects in A
    label   : human-readable identifier for display
    level   : depth in Hasse diagram (0 = TOP)
    """
    extent:  FrozenSet[str]
    intent:  FrozenSet[str]
    label:   str = ""
    level:   int = 0


@dataclass
class Implication:
    """
    Attribute implication  U → V  over M.
    Holds in K if every object having all attrs in U also has all in V.
    Part of the canonical (Duquenne-Guigues) implication base.
    """
    premise:    FrozenSet[str]    # U ⊆ M
    conclusion: FrozenSet[str]    # V ⊆ M, usually V \ U

    def __repr__(self) -> str:
        P = ", ".join(sorted(self.premise))
        C = ", ".join(sorted(self.conclusion))
        return f"{{{P}}} → {{{C}}}"


@dataclass
class ConceptLattice:
    """
    Concept lattice L(K)  [Ganter & Wille 1999, Theorem 2]

    concepts           : all formal concepts enumerated via NextClosure
    implications       : canonical implication base (Duquenne-Guigues base)
    hasse_edges        : list of (child_idx, parent_idx) for Hasse diagram
    context            : the underlying formal context
    """
    concepts:      List[FormalConcept] = field(default_factory=list)
    implications:  List[Implication]   = field(default_factory=list)
    hasse_edges:   List[Tuple[int,int]] = field(default_factory=list)
    context:       Optional[FormalContext] = None

    def add_concept(self, concept: FormalConcept) -> None:
        """Add concept if not already present (dedup by intent)."""
        for c in self.concepts:
            if c.intent == concept.intent:
                return
        self.concepts.append(concept)

    def find_by_intent(self, intent: FrozenSet[str]) -> Optional[FormalConcept]:
        for c in self.concepts:
            if c.intent == intent:
                return c
        return None

    def summary(self) -> str:
        return (f"ConceptLattice: {len(self.concepts)} concepts, "
                f"{len(self.implications)} implications, "
                f"{len(self.hasse_edges)} Hasse edges")


# ═══════════════════════════════════════════════════════════════════════════════
# 2.  NextClosure ALGORITHM — canonical concept enumeration
#     (Ganter 1984; Guigues & Duquenne 1986; Ganter & Wille 1999 §2.4)
# ═══════════════════════════════════════════════════════════════════════════════

def _lectic_next(
    current: List[bool],
    context: FormalContext,
    attr_order: List[str],
) -> Optional[List[bool]]:
    """
    Compute the lectic successor of 'current' attribute set in NextClosure.

    The lectic order on 2^M is: A <_i B  iff  i ∈ B\\A  and  A∩{0..i-1} = B∩{0..i-1}
    NextClosure advances to the smallest lectic successor that is closed.

    Algorithm (Ganter 1984):
      For i from |M|-1 down to 0:
        if i ∉ current:
          B = closure(current ∪ {i}) ∩ {0..i}
          if B is the i-lectically next (i.e., B and current agree on {0..i-1}
          and i ∈ B):
            return (current ∩ {0..i-1}) ∪ B
      return None  (current is the last closed set = M)
    """
    n = len(attr_order)
    for i in range(n - 1, -1, -1):
        if not current[i]:
            # Build candidate: (current ∩ {0..i-1}) ∪ {i}
            candidate_set = frozenset(
                attr_order[j] for j in range(i) if current[j]
            ) | {attr_order[i]}
            # Compute closure
            closed_set = context.closure(candidate_set)
            # Convert to bool array restricted to {0..i}
            closed_bits = [attr_order[j] in closed_set for j in range(n)]
            # Check lectic condition: agree on {0..i-1}, i ∈ closed
            agree = all(closed_bits[j] == current[j] for j in range(i))
            if agree and closed_bits[i]:
                return closed_bits
    return None


def enumerate_all_concepts(
    context: FormalContext,
    max_concepts: int = 2000,
) -> List[FormalConcept]:
    """
    Enumerate ALL formal concepts of K using NextClosure
    (Ganter 1984; Ganter & Wille 1999 §2.4).

    Starts from the smallest closed set (∅'' = M if no object has all attrs,
    or the closure of ∅), iterates in lectic order until exhausted.

    Returns list of FormalConcept ordered by lectic order of intent.

    Complexity: O(|G|·|M|·|L(K)|) where |L(K)| ≤ 2^min(|G|,|M|).
    For large contexts we cap at max_concepts to avoid exponential blowup
    (Poelmans et al. 2013 §5.5 — scalability).
    """
    attr_order = context.attributes   # fixed lectic order
    n = len(attr_order)

    concepts: List[FormalConcept] = []

    # Start: closure of ∅  (= intent of the TOP concept, since ∅' = G → G' = TOP intent)
    start_set = context.closure(frozenset())
    current = [a in start_set for a in attr_order]

    seen_intents: set = set()

    while True:
        intent = frozenset(a for a, v in zip(attr_order, current) if v)
        if intent not in seen_intents:
            seen_intents.add(intent)
            extent = context.attribute_prime(intent)
            concepts.append(FormalConcept(extent=extent, intent=intent))

        if len(concepts) >= max_concepts:
            break

        nxt = _lectic_next(current, context, attr_order)
        if nxt is None:
            break
        current = nxt

    return concepts


# ═══════════════════════════════════════════════════════════════════════════════
# 3.  Canonical Implication Base (Duquenne-Guigues base)
#     (Guigues & Duquenne 1986; Ganter & Wille 1999 §2.4)
# ═══════════════════════════════════════════════════════════════════════════════

def _lin_closure(
    attr_set: FrozenSet[str],
    implications: List[Implication],
) -> FrozenSet[str]:
    """
    LinClosure: compute the closure of attr_set under a set of implications
    in linear time (Beeri & Bernstein 1979; Poelmans et al. 2013 §5.1.1).

    Used by NextClosure to check whether a set is pseudo-closed.
    """
    result = set(attr_set)
    changed = True
    while changed:
        changed = False
        for impl in implications:
            if impl.premise <= result and not impl.conclusion <= result:
                result |= impl.conclusion
                changed = True
    return frozenset(result)


def compute_implication_base(
    context: FormalContext,
    max_implications: int = 500,
) -> List[Implication]:
    """
    Compute the canonical (Duquenne-Guigues) implication base of K.
    (Guigues & Duquenne 1986; Ganter 1984 NextClosure; Ganter & Wille 1999 §2.4)

    A set P ⊆ M is pseudo-closed if:
      (i)  P is not closed: P ≠ P''
      (ii) For every pseudo-closed Q ⊊ P: Q'' ⊆ P

    The canonical base is { P → P'' \\ P | P is pseudo-closed }.
    It is the unique smallest implication base (Guigues & Duquenne 1986).

    Implementation: Ganter's NextClosure where the closure operator is
    LinClosure under the implications collected SO FAR (not the context
    closure). At each set A that is closed w.r.t. the current implications we
    compare A with its context closure A''; if they differ, A is pseudo-closed
    and we emit A → A''\\A. (The earlier version advanced via the *context*
    closure, so it only ever visited closed sets and found no implications.)
    """
    attrs = context.attributes
    n = len(attrs)

    implications: List[Implication] = []

    def clo_L(idx_set: set) -> set:
        """LinClosure of an index set under the current implication list."""
        names = _lin_closure(frozenset(attrs[i] for i in idx_set), implications)
        return {i for i, a in enumerate(attrs) if a in names}

    def next_closure(A: set) -> Optional[set]:
        """Ganter NextClosure successor of A under closure operator clo_L."""
        A = set(A)
        for i in range(n - 1, -1, -1):
            if i in A:
                A.discard(i)
            else:
                B = clo_L(A | {i})
                # B is the successor iff B and A agree on every j < i
                if not any(j < i for j in (B - A)):
                    return B
        return None

    A: Optional[set] = clo_L(set())          # closure of ∅ under (empty) L
    iterations = 0
    max_iter = 200000

    while A is not None and iterations < max_iter:
        iterations += 1
        names_A = frozenset(attrs[i] for i in A)
        ctx_closed = context.closure(names_A)        # A''
        if names_A != ctx_closed:
            conclusion = ctx_closed - names_A
            if conclusion:
                implications.append(
                    Implication(premise=names_A, conclusion=conclusion))
                if len(implications) >= max_implications:
                    break
        if len(A) == n:                              # reached full set M
            break
        A = next_closure(A)

    return implications


# ═══════════════════════════════════════════════════════════════════════════════
# 4.  Hasse diagram construction
#     (Ganter & Wille 1999 §1.3 — line diagram of concept lattice)
# ═══════════════════════════════════════════════════════════════════════════════

def build_hasse_diagram(
    concepts: List[FormalConcept],
) -> List[Tuple[int, int]]:
    """
    Construct the Hasse diagram edges of the concept lattice
    (direct cover relations only, no transitive edges).

    (A1,B1) covers (A2,B2)  iff  A2 ⊂ A1 and ∄ C s.t. A2 ⊂ C ⊂ A1.
    Equivalently in terms of intents: B1 ⊂ B2 with no intermediate.

    Returns list of (child_idx, parent_idx) pairs.
    """
    n = len(concepts)
    # For each pair, check the subset relation on extents
    edges: List[Tuple[int, int]] = []

    for i in range(n):
        for j in range(n):
            if i == j:
                continue
            # i is candidate child, j is candidate parent
            if not concepts[i].extent < concepts[j].extent:
                continue
            # Check no intermediate concept
            is_direct = True
            for k in range(n):
                if k == i or k == j:
                    continue
                if concepts[i].extent < concepts[k].extent < concepts[j].extent:
                    is_direct = False
                    break
            if is_direct:
                edges.append((i, j))

    return edges


# ═══════════════════════════════════════════════════════════════════════════════
# 5.  FCABuilder — context construction from KB records
# ═══════════════════════════════════════════════════════════════════════════════

class FCABuilder:
    """
    Builds formal contexts and concept lattices from KB record dicts.

    Attribute set M:
      Following the induced-context approach of Kriegel (AAAI-24) and
      Rudolph (2004), attributes are derived from the record corpus:
        - domain/problem-type keywords from PROBLEM_TYPE_ATTRIBUTES
        - constraint keywords from record constraint field
        - structural CP keywords (variable types, constraint operators)
      This gives a finite M from which the incidence I is determined
      by whether (g,m) ∈ I, i.e. attribute m appears in record g's corpus.
    """

    def __init__(self, attribute_config: Dict[str, List[str]] | None = None):
        # Attribute set M is the catalog of named constraint TYPES + objectives
        # + problem-type anchors (paper: M = constraint types, objective
        # functions, solution properties). `attribute_config` is accepted for
        # backward compatibility but no longer drives incidence.
        try:
            from rag_fca import constraints as _con
        except Exception:
            from . import constraints as _con            # type: ignore
        self._con = _con
        self.attribute_config = attribute_config or {}
        self.all_attributes: List[str] = _con.all_named_attributes()

    # ── Context construction ─────────────────────────────────────────────────

    def build_context(self, records: List[Dict]) -> FormalContext:
        """
        Build the formal context K = (G, M, I) from KB records, faithfully to
        the paper (Methods → RAG-FCA, "Formal knowledge representation"):

          G  = problem instances (record ids)
          M  = named constraint types + objective functions + problem-type tags
          I  = (g, m) ∈ I  ⟺  problem g exhibits constraint/characteristic m

        Incidence for each record is computed by `constraints.attributes_for`,
        which uses the exact `Constraint` label when available and falls back
        to NL signature extraction otherwise. This yields a meaningful concept
        lattice whose concepts group problems by shared constraint subsets and
        whose implication base captures real constraint dependencies — unlike
        the previous substring-keyword scheme, which produced a degenerate
        lattice (e.g. the attribute "module" matched every record via the
        phrase "docplex.cp module").
        """
        objects    = [str(r["id"]) for r in records]
        attributes = self.all_attributes
        relation   = np.zeros((len(objects), len(attributes)), dtype=bool)
        attr_idx   = {a: i for i, a in enumerate(attributes)}

        for obj_i, rec in enumerate(records):
            for m in self._con.attributes_for(rec):
                j = attr_idx.get(m)
                if j is not None:
                    relation[obj_i, j] = True

        return FormalContext(
            objects=objects,
            attributes=attributes,
            relation=relation,
            object_data={str(r["id"]): r for r in records},
        )

    def build_fuzzy_context(
        self, records: List[Dict], decay: float = 0.7
    ) -> FuzzyFormalContext:
        """
        Build fuzzy formal context K_f = (G, M, I_f).
        (Singh et al. 2016 Def. 4; Poelmans et al. 2013 §5.4.1)

        I_f(g,m) ∈ [0,1] computed via logarithmic term frequency:
            µ(g,m) = min(1, decay · log(1 + count(m,corpus_g)) / log(1+10))
        Full structural match (from attribute_config) → I_f(g,m) = 1.0.
        """
        ctx = self.build_context(records)
        relation_f = ctx.relation.astype(float)
        attr_idx   = {a: i for i, a in enumerate(ctx.attributes)}

        for obj_i, rec in enumerate(records):
            corpus = " ".join([
                rec.get("nl_text", ""),
                rec.get("constraint_desc", ""),
                rec.get("cp_code", ""),
            ]).lower()
            for attr in ctx.attributes:
                if attr not in attr_idx:
                    continue
                col = attr_idx[attr]
                if relation_f[obj_i, col] == 1.0:
                    continue    # already fully present from structural match
                variants = [attr.lower(), attr.replace("_", " ").lower(),
                            attr.replace("_", "").lower()]
                count = sum(corpus.count(v) for v in variants)
                if count > 0:
                    mu = min(1.0, decay * math.log1p(count) / math.log1p(10))
                    relation_f[obj_i, col] = max(relation_f[obj_i, col], mu)

        return FuzzyFormalContext(
            objects=ctx.objects,
            attributes=ctx.attributes,
            relation_f=relation_f,
            object_data=ctx.object_data,
        )

    def build_lattice(
        self,
        context: FormalContext,
        max_concepts: int = 2000,
        compute_implications: bool = True,
        build_hasse: bool = True,
    ) -> ConceptLattice:
        """
        Build the full concept lattice L(K) via NextClosure.
        (Ganter 1984; Ganter & Wille 1999 §2.4; Poelmans et al. 2013 §2.1)

        Steps:
          1. Enumerate ALL formal concepts using NextClosure (lectic order)
          2. Assign human-readable labels and levels
          3. Optionally compute canonical implication base (Duquenne-Guigues)
          4. Optionally build Hasse diagram (cover relations)

        The TOP concept has extent=G (all objects), BOTTOM has extent=∅.
        Each concept (A,B) satisfies A'=B and B'=A exactly.
        """
        # ── Step 1: enumerate all formal concepts ────────────────────────────
        print(f"  [FCA] Enumerating formal concepts (NextClosure, max={max_concepts})...")
        concepts = enumerate_all_concepts(context, max_concepts=max_concepts)
        print(f"  [FCA] Found {len(concepts)} formal concepts |L(K)|={len(concepts)}")

        # ── Step 2: label concepts ───────────────────────────────────────────
        all_objects  = frozenset(context.objects)
        empty_extent = frozenset()

        for c in concepts:
            if c.extent == all_objects:
                c.label = "⊤ (TOP)"
                c.level = 0
            elif c.extent == empty_extent:
                c.label = "⊥ (BOTTOM)"
                c.level = 99
            else:
                # Label by dominant problem type in extent + first intent attrs
                type_counts: Dict[str, int] = {}
                for g in c.extent:
                    pt = context.object_data.get(g, {}).get("problem_type", "")
                    type_counts[pt] = type_counts.get(pt, 0) + 1
                dominant = max(type_counts, key=type_counts.get) if type_counts else ""
                label_attrs = sorted(c.intent)[:3]
                c.label = f"{dominant[:12]}|{','.join(label_attrs)}"
                # Level: inversely proportional to extent size
                c.level = 1 if len(c.extent) > len(context.objects) // 2 else (
                           2 if len(c.extent) > 1 else 3)

        # ── Step 3: canonical implication base ───────────────────────────────
        implications: List[Implication] = []
        if compute_implications and len(context.attributes) <= 64:
            print("  [FCA] Computing canonical implication base (Duquenne-Guigues)...")
            implications = compute_implication_base(context, max_implications=1000)
            print(f"  [FCA] Implication base: {len(implications)} implications")

        # ── Step 4: Hasse diagram ────────────────────────────────────────────
        hasse_edges: List[Tuple[int,int]] = []
        if build_hasse and len(concepts) <= 500:
            print("  [FCA] Building Hasse diagram (cover relations)...")
            hasse_edges = build_hasse_diagram(concepts)
            print(f"  [FCA] Hasse edges: {len(hasse_edges)}")

        lattice = ConceptLattice(
            concepts=concepts,
            implications=implications,
            hasse_edges=hasse_edges,
            context=context,
        )
        return lattice


# ═══════════════════════════════════════════════════════════════════════════════
# 6.  Similarity and Retrieval
# ═══════════════════════════════════════════════════════════════════════════════

def weighted_similarity(
    query_attrs: FrozenSet[str],
    concept_intent: FrozenSet[str],
    weights: Optional[Dict[str, float]] = None,
) -> float:
    """
    Weighted Jaccard similarity (Eq. 15):
        score(Q, B) = Σ_{m∈Q∩B} w(m) / Σ_{m∈Q∪B} w(m)
    """
    union = query_attrs | concept_intent
    inter = query_attrs & concept_intent
    if not union:
        return 0.0
    if weights:
        num = sum(weights.get(m, 1.0) for m in inter)
        den = sum(weights.get(m, 1.0) for m in union)
    else:
        num, den = len(inter), len(union)
    return num / den if den > 0 else 0.0


def fuzzy_similarity(
    query_memberships: Dict[str, float],
    concept_memberships: Dict[str, float],
    all_attributes: List[str],
    weights: Optional[Dict[str, float]] = None,
) -> float:
    """
    Fuzzy Jaccard similarity (Eq. 16):
        score_f(Q, B) = Σ_m w·min(µ_Q, µ_B) / Σ_m w·max(µ_Q, µ_B)
    """
    numerator = denominator = 0.0
    for m in all_attributes:
        w    = weights.get(m, 1.0) if weights else 1.0
        mu_q = query_memberships.get(m, 0.0)
        mu_b = concept_memberships.get(m, 0.0)
        numerator   += w * min(mu_q, mu_b)
        denominator += w * max(mu_q, mu_b)
    return numerator / denominator if denominator > 0 else 0.0


import re as _re_cue

# ── "" no-overlap ────────────────────────────────────
# eachonlyshould 4 x may matchedi.e.
# "vehicle" VRP
# "electric vehicle(s)" problem
# forcibly VRP "vehicle" must""
#
# VRP only depot / subtour / "vehicle routing" /
#  "vehicle arc" / fleet / truck / van / lorry / courier / TSP / CVRP / "last mile"
# / "route flow" / "traveling salesman" //DNA/
_DOMAIN_STRONG_CUES = {
    "Aircraft Skin Processing": [
        "makespan", "aircraft", "skin", "job shop", "job-shop", "flexible job",
        "processing time", "candidate machine", "setup time",
    ],
    "VRP": [
        "depot", "subtour", "sub-tour", "vehicle routing", "vehicle arc",
        "route flow", "fleet", "truck", "van", "lorry", "courier",
        "traveling salesman", "travelling salesman", "tsp", "cvrp", "vrp",
        "last mile", "last-mile",
    ],
    "Battery Pack Design": [
        "battery", "series column", "module voltage", "pack voltage",
        "energy loss", "reconfigurable", "battery module", "battery pack",
        "state of charge",
    ],
    "Charging Station Location": [
        "charging station", "facility location", "demand area",
        "candidate station", "candidate location", "service coverage",
        "charging facilit", "charging demand", "charging network",
    ],
    "DNA Sequence Design": [
        "dna", "nucleotide", "gc content", "gc-content", "watson", "base pair",
        "hamming distance", "reverse complement", "codon",
    ],
}

# nl_structuring import two derived
_VRP_STRONG_CUES  = tuple(_DOMAIN_STRONG_CUES["VRP"])
_FJSP_STRONG_CUES = tuple(_DOMAIN_STRONG_CUES["Aircraft Skin Processing"])


def _cue_in(cue: str, low: str) -> bool:
    """Cue match: multi-word phrases use substring match; single short words use
    word-boundary match, so 'van' does not hit 'advanced', 'arc' does not hit
    'search', and 'tsp'/'vrp' do not hit unrelated substrings."""
    if " " in cue or "-" in cue:
        return cue in low
    return _re_cue.search(r"\b" + _re_cue.escape(cue) + r"\b", low) is not None


def _strong_cue_hits(low: str) -> dict:
    return {dom: sum(1 for c in cues if _cue_in(c, low))
            for dom, cues in _DOMAIN_STRONG_CUES.items()}


def detect_scenario_strong(q: str) -> str:
    """Decide the scenario using domain-specific strong keywords only; return ''
    when uncertain.

    The strong keywords of the 5 domains do not overlap. Rules:
      - exactly one domain matches -> return it;
      - several match (rare) -> return only if one clearly leads (by >= 2),
        otherwise return '';
      - none match -> return '' (defer to FCA concept-overlap / weighted cues).

    Purpose: hard-localize the domain before any upper-level type is known, so
    VRP / charging / battery are not mislabeled by shared generic words. Note:
    'vehicle' is in no strong-keyword table, so charging/battery problems that
    mention 'electric vehicle' are not misclassified as VRP.
    """
    low = (q or "").lower()
    hits = _strong_cue_hits(low)
    present = {d: h for d, h in hits.items() if h > 0}
    if not present:
        return ""
    if len(present) == 1:
        return next(iter(present))
    ranked = sorted(present.items(), key=lambda kv: -kv[1])
    if ranked[0][1] - ranked[1][1] >= 2:
        return ranked[0][0]
    return ""  # strong keyworddistinct →


def _detect_scenario(q: str) -> str:
    """Detect the problem scenario from NL text (lowercased input).

    First try domain-specific strong keywords (detect_scenario_strong); return on
    a hit. Otherwise fall back to weighted cue counting, where cross-domain generic
    words (vehicle/machine/job/charging...) get low weight and specific words get
    high weight, so generic words do not dominate.
    """
    low = (q or "").lower()
    strong = detect_scenario_strong(low)
    if strong:
        return strong

    # but strong keywordalready
    domain_cues = {
        "Aircraft Skin Processing": [("aircraft", 3), ("skin", 3), ("job shop", 3),
            ("makespan", 3), ("processing time", 2), ("operation", 1),
            ("machine", 1), ("job", 1), ("robot", 1)],
        "Battery Pack Design":      [("battery", 3), ("module", 2), ("voltage", 2),
            ("energy storage", 2), ("photovoltaic", 2), ("series column", 3),
            ("energy loss", 2), ("pack", 1), ("cell", 1)],
        "Charging Station Location":[("charging station", 3), ("demand area", 3),
            ("facility location", 3), ("charging", 2), ("service coverage", 2),
            ("facility", 1), ("site", 1)],
        "DNA Sequence Design":      [("dna", 3), ("nucleotide", 3), ("gc content", 3),
            ("watson", 2), ("base pair", 2), ("sequence", 1)],
        "VRP":                      [("depot", 3), ("routing", 3), ("subtour", 3),
            ("truck", 3), ("fleet", 2), ("route", 2), ("customer", 2),
            ("delivery", 2), ("logistics", 1), ("deliver", 1),
            ("visited exactly once", 2), ("vehicle", 1)],
    }
    scen, best = None, 0
    for s, cues in domain_cues.items():
        hits = sum(w for c, w in cues if c in low)
        if hits > best:
            best, scen = hits, s
    return scen or ""


def extract_query_attributes(
    query_text: str, all_attributes: List[str], force_scenario: str = None,
    include_base: bool = True,
) -> FrozenSet[str]:
    """
    Extract the crisp attribute set Q' from a query (paper Eq. 15 semantic
    disambiguation). Three complementary signals:
      (a) detect the scenario from anchor/domain keywords → add its anchor;
      (b) apply the per-scenario NL constraint signatures (constraints.CATALOG)
          so phrasings like "tight start time window" map to the right named
          constraint type — not just literal attribute-name substrings;
      (c) fall back to attribute-name substring matching for any extras.

    force_scenario:
        Pass this when the upper level has reliably decided the type (e.g. the NL
        keyword detector confirmed 'VRP'). Then only that scenario's catalog is
        used (anchor + base + objective + matched optional signatures), and the
        cross-domain literal fallback (c) is SKIPPED, preventing other domains'
        (e.g. job-shop) attributes from leaking in. Otherwise, once a VRP text
        contains words like 'job'/'machine', FJSP attributes would be pulled in by
        (c) and drag retrieval back to job-shop concepts.

    include_base:
        When True (default) the scenario's *base* constraints are injected — this
        is what retrieval/augmentation needs. When False, the base set is NOT
        injected, so the result is the *explicitly stated* attribute set (anchor +
        objective + matched optional signatures). The rough-set implicit-constraint
        discovery (paper Alg., Eq. 19-22) must run on this explicit seed: if the
        base were already injected, the lower approximation (certain constraints)
        would be empty by construction, since those base constraints are exactly
        what the lower approximation is meant to *discover*.
    """
    import re as _re
    q = query_text.lower()
    found: set = set()

    try:
        from rag_fca import constraints as _con
    except Exception:
        _con = None

    scoped = bool(force_scenario)
    if _con is not None:
        # (a) scenario detection via robust domain disambiguation
        scen = force_scenario or _detect_scenario(q)

        scenarios = [scen] if scen else list(_con.CATALOG.keys())
        for s in scenarios:
            spec = _con.CATALOG.get(s)
            if not spec:
                continue
            found.add(spec["anchor"])
            # base constraints are implied by the scenario
            if include_base:
                found.update(spec["base"])
            found.add(spec["objective"])
            # (b) optional constraints via NL signatures
            for opt in spec["optional"]:
                if _re.search(opt["regex"], query_text):
                    if opt.get("relax"):
                        found.discard(opt["relax"])
                    found.add(opt["name"])

    # (c) literal attribute-name fallback only
    # VRP 'job'/'machine' FJSP
    if not scoped:
        for a in all_attributes:
            if a.lower() in q or a.replace("_", " ").lower() in q:
                found.add(a)

    return frozenset(a for a in found if a in all_attributes)


def extract_query_memberships(
    query_text: str, all_attributes: List[str]
) -> Dict[str, float]:
    """
    Extract fuzzy attribute memberships from query text.
    µ_Q(m) ∈ [0,1] via log term frequency.
    """
    q = query_text.lower()
    memberships: Dict[str, float] = {}
    for a in all_attributes:
        variants = [a.lower(), a.replace("_", " ").lower(), a.replace("_", "").lower()]
        count = sum(q.count(v) for v in variants)
        if count > 0:
            memberships[a] = min(1.0, math.log1p(count) / math.log1p(5))
    return memberships


# ═══════════════════════════════════════════════════════════════════════════════
# 7.  Rough-set implicit constraint discovery
#     (Eq. 19-22; Yao 2004; Poelmans et al. 2013 §5.4.2)
# ═══════════════════════════════════════════════════════════════════════════════

def discover_implicit_constraints(
    query_attrs: FrozenSet[str],
    lattice: ConceptLattice,
    context: FormalContext,
) -> Tuple[FrozenSet, FrozenSet]:
    """
    Rough-set lower/upper approximation for implicit constraint discovery.
    (Eq. 19-21; Yao 2004; Ganter & Wille 1999 §2.3)

    G_relevant = { g ∈ G | ∃(A,B) ∈ L(K): query_attrs ⊆ B ∧ g ∈ A }
              = lower approximation of query_attrs in L(K)

    certain_constraints  = { m ∈ M\\Q' | ∀g ∈ G_relevant, (g,m) ∈ I }
                         (lower approximation: must appear in all relevant records)
    possible_constraints = { m ∈ M\\Q' | ∃g ∈ G_relevant, (g,m) ∈ I }
                         (upper approximation: may appear in some relevant records)

    Q_augmented = Q' ∪ certain_constraints   (Eq. 22)
    """
    # G_relevant: union of extents of all concepts whose intent contains query_attrs
    g_relevant: FrozenSet[str] = frozenset()
    for concept in lattice.concepts:
        if query_attrs <= concept.intent:
            g_relevant = g_relevant | concept.extent

    if not g_relevant:
        return frozenset(), frozenset()

    obj_indices = [context.objects.index(g) for g in g_relevant if g in context.objects]
    if not obj_indices:
        return frozenset(), frozenset()

    certain  = set()
    possible = set()
    remaining = frozenset(context.attributes) - query_attrs

    for m in remaining:
        a_idx = context.attributes.index(m)
        col   = context.relation[obj_indices, a_idx]
        if np.all(col):
            certain.add(m)
        elif np.any(col):
            possible.add(m)

    return frozenset(certain), frozenset(possible)


def learn_attribute_weights(
    query_log: List[Tuple[FrozenSet[str], bool]],
    all_attributes: List[str],
    prior_weight: float = 1.0,
    positive_boost: float = 0.2,
    negative_decay: float = 0.05,
) -> Dict[str, float]:
    """
    Learn attribute importance weights from historical query logs.
    (Poelmans et al. 2013 §5: attribute implications and their use in retrieval)

    Positive feedback boosts weights; negative feedback decays them.
    Weights normalized to mean=1.0.
    """
    weights = {a: prior_weight for a in all_attributes}
    for attrs, success in query_log:
        delta = positive_boost if success else -negative_decay
        for a in attrs:
            if a in weights:
                weights[a] = max(0.1, weights[a] + delta)
    total = sum(weights.values())
    if total > 0:
        mean = total / len(weights)
        weights = {a: w / mean for a, w in weights.items()}
    return weights
